

name: 'Hello World'
description: 'Greet someone'
on:
  workflow_dispatch:
  
runs:
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-number::$(echo $RANDOM)"
      shell: bash
