name: deploy infra
concurrency:
  group: dev
  cancel-in-progress: false
on:
  repository_dispatch:
    types: [deploy_infra_dev]
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: sleep
        run: |
          sleep 20
          echo "coucoucoucou11"

      - name: Determine PULUMI env value
        run: echo "coucoucoucou"
