name: deploy infra
on:
  repository_dispatch:
    types: [deploy_infra_dev]
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Determine PULUMI env value
        run: echo "coucoucoucou"
