name: infra
concurrency:
  group: dev
  cancel-in-progress: false
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**"
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: infra
        run: |
          sleep 2
          echo "coucoucoucou"

      - name: Trigger test2
        run: |
          curl -X POST https://api.github.com/repos/godjirax/test-github-actions/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PAT_GITHUB_TOKEN }} \
          --data '{"event_type": "deploy_infra_dev", "client_payload": {"skip_data_migration":true, "skip_init_img":true, "skip_telemetry_img": true, "checkout_branch": "${{ github.ref_name }}", "env": "${{ env.PULUMI_ENV }}" }}'

