name: test2
on:
  push:
    branches:
      - main
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Determine PULUMI env value
        run: echo "coucoucoucou"
