name: Jackpot API & dependencies push (env. dev/staging)
concurrency: jackpot-io/dev
  workflow_dispatch:
    inputs:
      force_connectors:
        description: "Force connectors build & push"
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
jobs:
  push-docker-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Example 1
      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v38
        with:
          files: |
            base_sha: ${{ steps.get-base-sha.outputs.base_sha }}
            folder1/**
      # - name: Get changed files in the dependency docker folder
      #   id: changed-files-specific
      #   uses: tj-actions/changed-files@v37
      #   with:
      #     alll: |
      #       - '**/*'

      - name: Run 61616161
        # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
        if: steps.changed-files-yaml.outputs.any_changed == 'true'
        run: |
          echo "616161616161"
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.all_changed_files }}"

 
      # - name: List all changed files
      #   run: |
      #     for file in ${{ steps.changed-files.outputs.alll_changed_files }}; do
      #       echo "$file was changed"
      #     done
