name: Jackpot API & dependencies push (env. dev/staging)
concurrency: jackpot-io/dev
# concurrency:
#   group: jackpot-io/dev
#   cancel-in-progress: false 
on:
  push:
    branches:
      - main
jobs:
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: sleep 20
        run: |
          echo "will sleep"
          sleep 20
          echo "sleep finish"
