name: testtt
concurrency:
  group: tyty
  cancel-in-progress: false
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "folder2/file2"
      - "!folder1/file1"
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: sleep
        run: |
          sleep 10
          echo "coucoucoucou"

      - name: Trigger test2
        run: |
          curl -X POST https://api.github.com/repos/godjirax/test-github-actions/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PAT_GITHUB_TOKEN }} \
          --data '{"event_type": "deploy_infra_prod", "client_payload": {"skip_data_migration":true, "skip_init_img":true, "skip_telemetry_img": true, "checkout_branch": "${{ github.ref_name }}", "env": "${{ env.PULUMI_ENV }}" }}'

