name: test
on:
  push:
    branches:
      - main
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: test cal test2
        uses: ./.github/actions/test2/
        with:
          who-to-greet: 'Mona the Octocatdfdfdfdfdf'
