name: Jackpot API & dependencies push (env. dev/staging)
concurrency: jackpot-io/dev
on:
  push:
    branches:
      - main
jobs:
  push-docker-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files in the dependency docker folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v37
        with:
          files: |
            base_sha: ${{ steps.get-base-sha.outputs.base_sha }}
            ./**

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

