name: test
on:
  push:
    branches:
      - main
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

       - name: Run reusable workflow
        uses: ./reusable-actions/hello-world
        with:
          who-to-greet: 'Mona the Octocat'      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
